OUTPUT_DIR: './test/freesolv'
TAG: 'default'
SEED: 2022
NUM_FOLDS: 10
HYPER: True
HYPER_REMOVE: None
NUM_ITERS: 30


DATA:
  BATCH_SIZE: 128
  DATASET: 'freesolv'
  DATA_PATH: './data/freesolv/'
  TASK_TYPE: 'regression'
  METRIC: 'rmse'
  SPLIT_TYPE: 'random'
  AUG_FACTOR: 1


MODEL:
  GNN:
    HID_DIM: 256
    OUT_DIM: None
    DEPTH: 2
    DROPOUT: 0.1
    F_ATT: True
    BRICS: True
    SLICES: 1
    R: 4

  SEQ:
    OUT_DIM: 768

  ATT:
    NUM_HEADS: 4
    DROPOUT: 0.1


LOSS:
  FL_LOSS: True
  CL_LOSS: True
  ALPHA: 0.1
  TEMPERATURE: 0.1


TRAIN:
  EARLY_STOP: 40
  MAX_EPOCHS: 150

  # optimizer
  OPTIMIZER:
    TYPE: 'adam'
    # Learning rate
    BASE_LR: 8e-4
    # FPN Learning rate
    FP_LR: 4e-5
    # SGD momentum
    MOMENTUM: 0.9
    # Weight decay
    WEIGHT_DECAY: 1e-4

  # LR scheduler
  LR_SCHEDULER:
    TYPE: 'reduce'
    # NoamLR parameters
    WARMUP_EPOCHS: 2.0
    INIT_LR: 1e-4
    MAX_LR: 1e-2
    FINAL_LR: 1e-4

    # ReduceLRonPlateau
    FACTOR: 0.5
    PATIENCE: 15
    MIN_LR: 1e-5

  RESUME: None

